import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// PhotoEnhancerUnblur — generated by AppFactoryKit appgen from niche "photo-enhancer".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum PhotoEnhancerUnblurFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "PhotoEnhancerUnblur",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "wand.and.stars",
                          title: "PhotoEnhancerUnblur",
                          message: "Upscale, sharpen and deblur photos."),
                    .init(systemImage: "photo.on.rectangle.angled",
                          title: "Go Pro",
                          message: "4K upscale, batch, no watermark.")
                ],
                presentsPaywallOnFinish: true,
                accent: .purple
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock PhotoEnhancerUnblur Pro",
                subheadline: "4K upscale, batch, no watermark.",
                benefits: [
                    .init(systemImage: "infinity", title: "4K upscale"),
                    .init(systemImage: "bolt.fill", title: "Batch"),
                    .init(systemImage: "nosign", title: "No watermark")
                ],
                productIDs: ["photo-enhancer_yearly", "photo-enhancer_weekly"],
                highlightedProductID: "photo-enhancer_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .purple, heroSystemImage: "wand.and.stars")
            )
        )
        return AppFactory(config)
    }
}

@main
struct PhotoEnhancerUnblurApp: App {
    @StateObject private var factory = PhotoEnhancerUnblurFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.purple)
        }
    }
}
